name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  pr_status_check:
    runs-on: ubuntu-latest
    timeout-minutes:  15

    steps:
      - uses: actions/checkout@v2

      - name: Build docker-compose
        run: docker-compose -f docker-compose.ci.yml up --build -d
