name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  pr_status_check:
    name: PR Status Check
    runs-on: ubuntu-latest
    timeout-minutes:  15

    container:
      image: node:16-bullseye

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    env:
      NODE_ENV: 'ci'
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: auth_server
      DB_USERNAME: test
      DB_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
      
      - name: Test
        run: npm run test
