name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  pr_status_check:
    runs-on: ubuntu-latest
    timeout-minutes:  15

    steps:
      - uses: actions/checkout@v2

      - name: Build docker-compose
        run: docker-compose up -d
      
      - name: Linting
        run: docker-compose exec auth-server npm run lint

      - name: Testing
        run: docker-compose exec auth-server npm run test
