name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes:  15

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t auth-server-test --target=base
      
      - name: Linting
        run: docker run -i auth-server-test sh -c "npm run lint" 

      - name: Testing
        run: docker run -i auth-server-test sh -c "npm run test" 
